# Generated by Django 5.1.2 on 2024-10-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Tax',
        ),
    ]
