# Generated by Django 5.1.2 on 2024-10-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_text_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='name',
            new_name='tax_name',
        ),
        migrations.RenameField(
            model_name='tax',
            old_name='rate',
            new_name='tax_rate',
        ),
    ]
