# Generated by Django 5.1.2 on 2024-10-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_name_tax_tax_name_rename_rate_tax_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
