# Generated by Django 5.1.2 on 2024-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_tax_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
