# Generated by Django 5.1.3 on 2024-11-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
