# Generated by Django 5.1.3 on 2024-11-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_tax_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxOraganization', to='organization.organization'),
        ),
    ]
