# Generated by Django 5.1.3 on 2024-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_organization_tax_alter_tax_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
