# Generated by Django 5.1.3 on 2024-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
