# Generated by Django 5.1.3 on 2024-11-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_remove_organization_tax_remove_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
