# Generated by Django 5.1.3 on 2024-11-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0014_alter_inventoryitem_account'),
        ('project', '0001_initial'),
        ('users', '0003_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('p_start_date', models.DateTimeField(auto_now_add=True)),
                ('p_end_date', models.DateTimeField(auto_now_add=True)),
                ('p_status', models.CharField(choices=[('create', 'Create'), ('waiting_approval', 'Waiting_approval'), ('approve', 'Approve'), ('started', 'Started'), ('ended', 'Ended')], max_length=32)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='users.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Pdocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='documents/productions')),
                ('Production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('approved_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.orderunit')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.production')),
            ],
        ),
    ]
