# Generated by Django 5.1.3 on 2024-11-11 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdocument',
            name='Production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producstiondocs', to='production.production'),
        ),
    ]
