# Generated by Django 5.1.3 on 2024-11-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_pdocument_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdocument',
            old_name='docs',
            new_name='docfile',
        ),
        migrations.AddField(
            model_name='pdocument',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdocument',
            name='Production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='production.production'),
        ),
    ]
