# Generated by Django 5.1.3 on 2024-11-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_docs_pdocument_docfile_pdocument_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdocument',
            old_name='Production',
            new_name='production',
        ),
    ]
