# Generated by Django 5.1.2 on 2024-10-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('inventory', '__first__'),
        ('organization', '0005_alter_tax_tax_rate'),
        ('users', '0003_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('partially_received', 'Partially_Received'), ('complted', 'Completd')], max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.legeracc')),
                ('measureUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderunit')),
                ('tax_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.tax')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_number', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now=True)),
                ('ship_to', models.CharField(max_length=100)),
                ('bill_to', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('sent', 'Sent'), ('paritially_Received', 'Paritially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_sales', to='users.customuser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sales', to='users.customuser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesitem')),
            ],
        ),
    ]
