# Generated by Django 5.1.3 on 2024-11-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('inventory', '0003_initial'),
        ('organization', '0001_initial'),
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_sales', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='sales',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sales', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='sales',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.issueunit'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sales'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.tax'),
        ),
    ]
