# Generated by Django 5.1.3 on 2024-11-12 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventoryitem_account'),
        ('sales', '0002_alter_salesitem_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='items',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='total',
        ),
        migrations.AddField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='item_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesitem',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='sales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesitem',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('sent', 'Sent'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='measureUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.issueunit'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('completed', 'Completed')], max_length=100),
        ),
    ]
