# Generated by Django 5.1.3 on 2024-11-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sales_items_remove_salesitem_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='measureUnit',
            new_name='measure_unit',
        ),
    ]
