# Generated by Django 5.1.2 on 2024-10-17 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('s_date', models.DateField(auto_now=True)),
                ('e_date', models.DateField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('t_date', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('description', models.TextField(max_length=200)),
                ('type', models.CharField(max_length=30)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='journal.journal')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journal.transaction'),
        ),
    ]
