# Generated by Django 5.1.2 on 2024-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=7),
        ),
    ]
