# Generated by Django 5.1.2 on 2024-10-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='journal',
        ),
    ]
