# Generated by Django 5.1.2 on 2024-10-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_transaction_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='journalID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='journal.journal'),
        ),
    ]
