# Generated by Django 5.1.2 on 2024-10-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('journal', '0004_remove_journal_transaction_transaction_journalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Leger Account+', to='account.legeracc'),
        ),
    ]
