# Generated by Django 5.1.3 on 2024-11-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('inventory', '0003_initial'),
        ('organization', '0001_initial'),
        ('purchaseOrder', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderunit'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchaseOrder.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderunit'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchaseOrder.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.tax'),
        ),
    ]
