# Generated by Django 5.1.3 on 2024-11-11 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='documents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchaseOrder.purchasedocument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchaseOrder.purchaseorder'),
        ),
    ]
