# Generated by Django 5.1.3 on 2024-11-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0003_remove_purchaseorder_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedocument',
            old_name='name',
            new_name='doc_name',
        ),
        migrations.RenameField(
            model_name='purchasedocument',
            old_name='doc',
            new_name='docfile',
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchaseOrder.purchaseorder'),
        ),
    ]
