# Generated by Django 5.1.3 on 2024-11-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_manufacturer', models.CharField(max_length=100)),
                ('item_manufacturer_code', models.CharField(max_length=100)),
                ('item_quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IssueUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.PositiveIntegerField()),
                ('notes', models.CharField(max_length=100)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('doc_file', models.FileField(upload_to='documents/reception')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_manufacturer', models.CharField(max_length=100)),
                ('item_manufacturer_code', models.CharField(max_length=100)),
                ('item_quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reserved_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancel', 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_manufacturer', models.CharField(max_length=100)),
                ('item_manufacturer_code', models.CharField(max_length=100)),
                ('item_quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Storeroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('bill_to', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trans_number', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('transfered', 'Transfered')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransfertItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_manufacturer', models.CharField(max_length=100)),
                ('item_manufacturer_code', models.CharField(max_length=100)),
                ('item_quantity', models.FloatField()),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('partially_approve', 'Partially Approve'), ('declined', 'Declined')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('min_quantity', models.FloatField()),
                ('max_quantity', models.FloatField()),
                ('current_balance', models.FloatField()),
                ('physical_count', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/inventory_images/')),
                ('reorder', models.BooleanField(default=False)),
                ('reorder_point', models.FloatField()),
                ('reorder_quantity', models.FloatField()),
                ('type', models.CharField(choices=[('finished', 'Finished'), ('unfinished', 'Unfinished')], max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ledgeraccount')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bin')),
            ],
        ),
    ]
