# Generated by Django 5.1.2 on 2024-10-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_transfertitem_transfert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfertitem',
            old_name='Bin',
            new_name='item_bin',
        ),
        migrations.RenameField(
            model_name='transfertitem',
            old_name='descripton',
            new_name='item_descripton',
        ),
        migrations.RenameField(
            model_name='transfertitem',
            old_name='manufacturer',
            new_name='item_manufacturer',
        ),
        migrations.RenameField(
            model_name='transfertitem',
            old_name='manufactures_code',
            new_name='item_manufactures_code',
        ),
        migrations.RenameField(
            model_name='transfertitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='transfertitem',
            old_name='quantity',
            new_name='item_quantity',
        ),
    ]
