# Generated by Django 5.1.2 on 2024-10-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_bin_transfertitem_item_bin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfertitem',
            old_name='item_descripton',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='transfertitem',
            old_name='item_manufactures_code',
            new_name='item_manufacCode',
        ),
    ]
