# Generated by Django 5.1.2 on 2024-10-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_item_descripton_transfertitem_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='bin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.bin'),
            preserve_default=False,
        ),
    ]
