# Generated by Django 5.1.2 on 2024-10-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_transfert_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfert',
            old_name='data',
            new_name='date',
        ),
    ]
