# Generated by Django 5.1.2 on 2024-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_data_transfert_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='issue_Unit',
            new_name='issue_unit',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='order_Unit',
            new_name='order_unit',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='preferate_supplier',
            new_name='preferred_supplier',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
