# Generated by Django 5.1.2 on 2024-10-30 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_issue_unit_inventoryitem_issue_unit_and_more'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='suppliers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='supplier.supplier'),
            preserve_default=False,
        ),
    ]
