# Generated by Django 5.1.2 on 2024-10-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventoryitem_suppliers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='code',
        ),
    ]
