# Generated by Django 5.1.3 on 2024-11-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_item_type_inventoryitem_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='recep_doc',
        ),
    ]
