# Generated by Django 5.1.3 on 2024-11-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventoryitem_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='pur_order',
            new_name='po_number',
        ),
        migrations.RemoveField(
            model_name='receptiondoc',
            name='docs',
        ),
        migrations.AddField(
            model_name='receptiondoc',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptiondoc',
            name='doc_file',
            field=models.FileField(default=1, upload_to='documents/reception'),
            preserve_default=False,
        ),
    ]
