# Generated by Django 5.1.3 on 2024-11-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_pur_order_reception_po_number_and_more'),
        ('purchaseOrder', '0005_alter_purchasedocument_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='purchase_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrder', to='purchaseOrder.purchaseorder'),
            preserve_default=False,
        ),
    ]
