# Generated by Django 5.1.3 on 2024-11-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_item_manufaccode_reservationitem_item_manufacturer_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionitem',
            old_name='item_manufacCode',
            new_name='item_manufacturer_code',
        ),
    ]
