# Generated by Django 5.1.3 on 2024-11-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_reservation_project_alter_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueitem',
            old_name='item_manufacCode',
            new_name='item_manufacturer_code',
        ),
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
