# Generated by Django 5.1.3 on 2024-11-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_item_manufaccode_issueitem_item_manufacturer_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfertitem',
            old_name='item_manufacCode',
            new_name='item_manufacturer_code',
        ),
    ]
