# Generated by Django 5.1.3 on 2024-11-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialBalance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialbalance',
            old_name='account',
            new_name='t_account',
        ),
    ]
