# Generated by Django 5.1.2 on 2024-10-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0003_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('billing_address', models.TextField(max_length=200)),
                ('shipping_address', models.TextField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('sku', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('growth', models.BooleanField(default=False)),
                ('growth_fre', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quaters', 'Monthly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly')], max_length=100)),
                ('growth_ercnetage', models.FloatField()),
                ('measureUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderunit')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
