# Generated by Django 5.1.3 on 2024-11-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_rename_measureunit_supplieritem_measure_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplieritem',
            old_name='growth_ercnetage',
            new_name='growth_percentage',
        ),
    ]
