# Generated by Django 5.1.3 on 2024-11-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_rename_name_shipdocs_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipdocs',
            old_name='docs',
            new_name='doc_file',
        ),
        migrations.RenameField(
            model_name='shipdocs',
            old_name='file_name',
            new_name='doc_name',
        ),
    ]
