# Generated by Django 5.1.3 on 2024-11-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_rename_growth_ercnetage_supplieritem_growth_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplieritem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_items', to='supplier.supplier'),
        ),
    ]
