# Generated by Django 5.1.3 on 2024-11-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_rename_item_name_supplieritem_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplieritem',
            old_name='growth_percentage',
            new_name='growth_per',
        ),
    ]
