# Generated by Django 5.1.3 on 2024-11-11 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_rename_growth_percentage_supplieritem_growth_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contact', to='supplier.supplier'),
        ),
    ]
