# Generated by Django 5.1.3 on 2024-11-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legeracc',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='legeracc',
            name='type_status',
            field=models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10),
        ),
    ]
