# Generated by Django 5.1.3 on 2024-11-07 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_subaccount_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='account.legeracc'),
            preserve_default=False,
        ),
    ]
