# Generated by Django 5.1.3 on 2024-11-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_subaccount_parent'),
        ('bill', '0001_initial'),
        ('inventory', '0013_remove_reservation_recep_doc'),
        ('invoice', '0002_alter_invoiceitem_account_and_more'),
        ('journal', '0006_alter_transaction_account'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegerAcc',
            new_name='LegerAccount',
        ),
        migrations.CreateModel(
            name='SubSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_accounts', to='account.legeraccount')),
            ],
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_account', to='account.subsaccount'),
        ),
    ]
