# Generated by Django 5.1.3 on 2024-11-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_legeracc_legeraccount_subsaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legeraccount',
            old_name='name',
            new_name='LegerName',
        ),
    ]
