# Generated by Django 5.1.2 on 2024-10-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('inventory', '__first__'),
        ('organization', '0005_alter_tax_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='documents/bills')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.legeracc')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderunit')),
                ('tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.tax')),
            ],
        ),
    ]
