# Generated by Django 5.1.3 on 2024-11-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_billitem_account'),
        ('purchaseOrder', '0005_alter_purchasedocument_docfile'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdoc',
            old_name='docs',
            new_name='doc_file',
        ),
        migrations.RenameField(
            model_name='billitem',
            old_name='total',
            new_name='net_amount',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='billdoc',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_num', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
                ('required_date', models.DateField()),
                ('status', models.CharField(choices=[('need approval', 'Need approval'), ('approve', 'Approve'), ('waiting Payment', 'Waiting Payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('close', 'Close')], max_length=20)),
                ('ship_to', models.CharField(default='Default Value', max_length=100)),
                ('bill_to', models.CharField(default='Default Value', max_length=100)),
                ('total_nat_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_tax_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercontact')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseOrder.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.terms')),
            ],
        ),
        migrations.AddField(
            model_name='billdoc',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billDocs', to='bill.bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.bill'),
            preserve_default=False,
        ),
    ]
