# Generated by Django 5.1.3 on 2024-11-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_rename_docs_billdoc_doc_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ship_to',
            field=models.CharField(max_length=100),
        ),
    ]
