# Generated by Django 5.1.3 on 2024-11-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_bill_bill_to_alter_bill_ship_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='total_nat_amount',
            new_name='total_net_amount',
        ),
    ]
