# Generated by Django 5.1.3 on 2024-11-19 08:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the shipping carrier', max_length=100, unique=True)),
                ('tracking_url', models.URLField(blank=True, help_text='Base URL for tracking shipments')),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number for the carrier', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this carrier is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of the note', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_num', models.PositiveIntegerField(help_text='Unique shipping tracking number', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('shipping_name', models.CharField(help_text='Name or description of the shipment', max_length=50)),
                ('shipping_date', models.DateField(help_text='Date when the shipment was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipping.carrier')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipping.notes')),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shippings',
                'ordering': ['-shipping_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the shipped item', max_length=100)),
                ('description', models.CharField(help_text='Name of the shipped item', max_length=100)),
                ('manufacturer', models.CharField(help_text='Manufacturer of the shipped item', max_length=100)),
                ('manufacturer_code', models.CharField(help_text='Manufacturer code of the shipped item', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of items', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipping')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
