# Generated by Django 5.1.3 on 2024-11-19 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        ('shipping', '0002_alter_shippingitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='other',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('others', 'Others')], default='transfer', help_text='Type of shipment', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='sales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.sales'),
            preserve_default=False,
        ),
    ]
