# Generated by Django 5.1.3 on 2024-11-05 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('client', '0001_initial'),
        ('inventory', '0012_rename_item_type_inventoryitem_type_and_more'),
        ('organization', '0005_alter_tax_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='documents/invoices')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.legeracc')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.issueunit')),
                ('tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.tax')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now=True)),
                ('required_date', models.DateField()),
                ('status', models.CharField(choices=[('need approval', 'Need approval'), ('approve', 'Approve'), ('waiting Payment', 'Waiting Payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('close', 'Close')], max_length=20)),
                ('ship_to', models.CharField(max_length=100)),
                ('bill_to', models.CharField(max_length=100)),
                ('total_tax_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_net_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('turn_to_pdf', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.contact')),
                ('docs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicedoc')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceItems', to='invoice.invoiceitem')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.terms')),
            ],
        ),
    ]
