# Generated by Django 5.1.3 on 2024-11-07 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_subaccount_parent'),
        ('inventory', '0012_rename_item_type_inventoryitem_type_and_more'),
        ('invoice', '0001_initial'),
        ('organization', '0006_organization_created_at_organization_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='account.legeracc'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='inventory.issueunit'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='organization.tax'),
        ),
    ]
