# Generated by Django 5.1.2 on 2024-10-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('required_date', models.DateField()),
                ('status', models.CharField(choices=[('Need approval', 'Need approval'), ('Approve', 'Approve'), ('Waiting Payment', 'Waiting Payment'), ('Paid', 'Paid'), ('Close / Complete', 'Close / Complete')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=40)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('account', models.CharField(max_length=100)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceitem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.supplier'),
        ),
        migrations.AddField(
            model_name='contact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.supplier'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.taxitem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.taxitem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.terms'),
        ),
    ]
