# Generated by Django 5.1.2 on 2024-10-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_contact_invoice_invoiceitem_supplier_taxitem_terms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='invoice_num',
        ),
    ]
