# Generated by Django 5.1.3 on 2024-11-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoiceitem_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='net_amount',
            field=models.DecimalField(decimal_places=3, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
