# Generated by Django 5.1.2 on 2024-10-17 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rename_invoice_number_invoice_invoice_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('docs', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='required_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.taxitem'),
        ),
    ]
