# Generated by Django 5.1.3 on 2024-11-08 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_items_remove_invoiceitem_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='docs',
        ),
        migrations.AddField(
            model_name='invoicedoc',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceDocs', to='invoice.invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('need approval', 'Need approval'), ('approved', 'Approved'), ('waiting payment', 'Waiting Payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('close', 'Close')], max_length=20),
        ),
    ]
