# Generated by Django 5.1.3 on 2024-11-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_ledgeraccount_remove_subaccount_leger_account_and_more'),
        ('invoice', '0004_remove_invoice_docs_invoicedoc_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='account.ledgeraccount'),
        ),
    ]
