# Generated by Django 5.1.2 on 2024-10-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_document_invoice_bill_to_invoice_ship_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.document'),
        ),
    ]
