# Generated by Django 5.1.2 on 2024-10-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_docs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax_item',
            new_name='tax',
        ),
    ]
