# Generated by Django 5.1.3 on 2024-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoiceitem_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedoc',
            old_name='docs',
            new_name='doc_file',
        ),
        migrations.AddField(
            model_name='invoicedoc',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
