# Generated by Django 5.1.2 on 2024-10-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_rename_tax_item_invoice_tax'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxItem',
            new_name='TaxInfo',
        ),
    ]
