# Generated by Django 5.1.2 on 2024-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_taxitem_taxinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='account',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
