# Generated by Django 5.1.2 on 2024-10-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_invoiceitem_account_alter_invoiceitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.supplier'),
        ),
    ]
