# Generated by Django 5.1.2 on 2024-10-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_contact_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.supplier'),
        ),
    ]
