# Generated by Django 5.1.2 on 2024-10-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_contact_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docs',
            field=models.CharField(max_length=10),
        ),
    ]
