# Generated by Django 5.1.3 on 2024-11-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0012_rename_item_type_inventoryitem_type_and_more'),
        ('organization', '0006_organization_created_at_organization_updated_at'),
        ('supplier', '0001_initial'),
        ('users', '0003_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='documents/requisition')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('ship_to', models.CharField(max_length=100)),
                ('bill_to', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('inProgress', 'In Progress'), ('approved', 'Approved'), ('created', 'Created'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancel', 'Cancel')], max_length=20)),
                ('total_tax_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('total_net_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_requisitions', to='users.customuser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requisitions', to='users.customuser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('docs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitiondocs', to='requisition.requisitiondoc')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('reception_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('measureUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderunit')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisition.requisition')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.tax')),
            ],
        ),
    ]
