# Generated by Django 5.1.3 on 2024-11-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('ship_to', models.CharField(max_length=100)),
                ('bill_to', models.CharField(max_length=100)),
                ('total_tax_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
                ('total_net_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('inProgress', 'In Progress'), ('approved', 'Approved'), ('created', 'Created'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancel', 'Cancel')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='documents/requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('reception_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
