# Generated by Django 5.1.3 on 2024-11-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionitem',
            old_name='total_amount',
            new_name='net_amount',
        ),
    ]
