# Generated by Django 5.1.3 on 2024-11-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_created_at_organization_updated_at'),
        ('requisition', '0002_rename_total_amount_requisitionitem_net_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_items', to='organization.tax'),
        ),
    ]
