# Generated by Django 5.1.3 on 2024-11-08 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_alter_requisitionitem_tax_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitiondoc',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_docs', to='requisition.requisition'),
            preserve_default=False,
        ),
    ]
