# Generated by Django 5.1.2 on 2024-10-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_alter_tax_tax_rate'),
        ('users', '0003_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='documents/requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('measureUnit', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=100)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('totals', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reception_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now=True)),
                ('ship_to', models.CharField(max_length=100)),
                ('bill_to', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('inProgress', 'In Progress'), ('approved', 'Approved'), ('created', 'Created'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancel', 'Cancel')], max_length=20)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_requisitions', to='users.customuser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requisitions', to='users.customuser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('docs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.requisitiondoc')),
            ],
        ),
    ]
