# Generated by Django 5.1.2 on 2024-10-31 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_item_type_inventoryitem_type_and_more'),
        ('requisition', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='measureUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderunit'),
        ),
    ]
