# Generated by Django 5.1.2 on 2024-10-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_alter_requisitionitem_measureunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionitem',
            old_name='totals',
            new_name='totals_amount',
        ),
    ]
