# Generated by Django 5.1.2 on 2024-10-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0005_rename_totals_amount_requisitionitem_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='total_amount_before_tax',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
