# Generated by Django 5.1.2 on 2024-10-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0006_requisition_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='created_date',
            new_name='date',
        ),
    ]
