# Generated by Django 5.1.2 on 2024-10-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0007_rename_created_date_requisition_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='created_by',
        ),
    ]
