# Generated by Django 5.1.2 on 2024-10-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0009_requisition_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitiondoc',
            name='docs',
            field=models.FileField(default=1, upload_to='documents/requisition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisitiondoc',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
