# Generated by Django 5.1.2 on 2024-10-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0013_rename_total_amount_before_tax_requisition_total_net_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='docs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitionItems', to='requisition.requisitiondoc'),
        ),
    ]
