# Generated by Django 5.1.2 on 2024-10-31 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0014_alter_requisition_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='items',
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisition.requisition'),
            preserve_default=False,
        ),
    ]
