# Generated by Django 5.1.3 on 2024-11-07 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0016_alter_requisition_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='docs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitiondocs', to='requisition.requisitiondoc'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_items', to='requisition.requisition'),
        ),
    ]
